spring:
  neo4j:
    uri: bolt://localhost:11005
    authentication:
      username: neo4j
      password: 12345678
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

spring.devtools:
  restart:
    enabled: true

server:
  servlet:
    context-path: /neo4j
  port: 11010

