spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

spring.devtools:
  restart:
    enabled: true

server:
  servlet:
    context-path: /neo4j
  port: 8082

rdf:
  namespaces:
    block: http://example.org/block#
    Property: http://example.org/property#
    rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
    xsd: http://www.w3.org/2001/XMLSchema#